// This file was autogenerated by some hot garbage in the `uniffi` crate.
// Trust me, you don't want to mess with it!

// swiftlint:disable all
import Foundation

// Depending on the consumer's build setup, the low-level FFI code
// might be in a separate module, or it might be compiled inline into
// this module. This is a bit of light hackery to work with both.
#if canImport(prism_ffiFFI)
import prism_ffiFFI
#endif

fileprivate extension RustBuffer {
    // Allocate a new buffer, copying the contents of a `UInt8` array.
    init(bytes: [UInt8]) {
        let rbuf = bytes.withUnsafeBufferPointer { ptr in
            RustBuffer.from(ptr)
        }
        self.init(capacity: rbuf.capacity, len: rbuf.len, data: rbuf.data)
    }

    static func empty() -> RustBuffer {
        RustBuffer(capacity: 0, len:0, data: nil)
    }

    static func from(_ ptr: UnsafeBufferPointer<UInt8>) -> RustBuffer {
        try! rustCall { ffi_prism_ffi_rustbuffer_from_bytes(ForeignBytes(bufferPointer: ptr), $0) }
    }

    // Frees the buffer in place.
    // The buffer must not be used after this is called.
    func deallocate() {
        try! rustCall { ffi_prism_ffi_rustbuffer_free(self, $0) }
    }
}

fileprivate extension ForeignBytes {
    init(bufferPointer: UnsafeBufferPointer<UInt8>) {
        self.init(len: Int32(bufferPointer.count), data: bufferPointer.baseAddress)
    }
}

// For every type used in the interface, we provide helper methods for conveniently
// lifting and lowering that type from C-compatible data, and for reading and writing
// values of that type in a buffer.

// Helper classes/extensions that don't change.
// Someday, this will be in a library of its own.

fileprivate extension Data {
    init(rustBuffer: RustBuffer) {
        self.init(
            bytesNoCopy: rustBuffer.data!,
            count: Int(rustBuffer.len),
            deallocator: .none
        )
    }
}

// Define reader functionality.  Normally this would be defined in a class or
// struct, but we use standalone functions instead in order to make external
// types work.
//
// With external types, one swift source file needs to be able to call the read
// method on another source file's FfiConverter, but then what visibility
// should Reader have?
// - If Reader is fileprivate, then this means the read() must also
//   be fileprivate, which doesn't work with external types.
// - If Reader is internal/public, we'll get compile errors since both source
//   files will try define the same type.
//
// Instead, the read() method and these helper functions input a tuple of data

fileprivate func createReader(data: Data) -> (data: Data, offset: Data.Index) {
    (data: data, offset: 0)
}

// Reads an integer at the current offset, in big-endian order, and advances
// the offset on success. Throws if reading the integer would move the
// offset past the end of the buffer.
fileprivate func readInt<T: FixedWidthInteger>(_ reader: inout (data: Data, offset: Data.Index)) throws -> T {
    let range = reader.offset..<reader.offset + MemoryLayout<T>.size
    guard reader.data.count >= range.upperBound else {
        throw UniffiInternalError.bufferOverflow
    }
    if T.self == UInt8.self {
        let value = reader.data[reader.offset]
        reader.offset += 1
        return value as! T
    }
    var value: T = 0
    let _ = withUnsafeMutableBytes(of: &value, { reader.data.copyBytes(to: $0, from: range)})
    reader.offset = range.upperBound
    return value.bigEndian
}

// Reads an arbitrary number of bytes, to be used to read
// raw bytes, this is useful when lifting strings
fileprivate func readBytes(_ reader: inout (data: Data, offset: Data.Index), count: Int) throws -> Array<UInt8> {
    let range = reader.offset..<(reader.offset+count)
    guard reader.data.count >= range.upperBound else {
        throw UniffiInternalError.bufferOverflow
    }
    var value = [UInt8](repeating: 0, count: count)
    value.withUnsafeMutableBufferPointer({ buffer in
        reader.data.copyBytes(to: buffer, from: range)
    })
    reader.offset = range.upperBound
    return value
}

// Reads a float at the current offset.
fileprivate func readFloat(_ reader: inout (data: Data, offset: Data.Index)) throws -> Float {
    return Float(bitPattern: try readInt(&reader))
}

// Reads a float at the current offset.
fileprivate func readDouble(_ reader: inout (data: Data, offset: Data.Index)) throws -> Double {
    return Double(bitPattern: try readInt(&reader))
}

// Indicates if the offset has reached the end of the buffer.
fileprivate func hasRemaining(_ reader: (data: Data, offset: Data.Index)) -> Bool {
    return reader.offset < reader.data.count
}

// Define writer functionality.  Normally this would be defined in a class or
// struct, but we use standalone functions instead in order to make external
// types work.  See the above discussion on Readers for details.

fileprivate func createWriter() -> [UInt8] {
    return []
}

fileprivate func writeBytes<S>(_ writer: inout [UInt8], _ byteArr: S) where S: Sequence, S.Element == UInt8 {
    writer.append(contentsOf: byteArr)
}

// Writes an integer in big-endian order.
//
// Warning: make sure what you are trying to write
// is in the correct type!
fileprivate func writeInt<T: FixedWidthInteger>(_ writer: inout [UInt8], _ value: T) {
    var value = value.bigEndian
    withUnsafeBytes(of: &value) { writer.append(contentsOf: $0) }
}

fileprivate func writeFloat(_ writer: inout [UInt8], _ value: Float) {
    writeInt(&writer, value.bitPattern)
}

fileprivate func writeDouble(_ writer: inout [UInt8], _ value: Double) {
    writeInt(&writer, value.bitPattern)
}

// Protocol for types that transfer other types across the FFI. This is
// analogous to the Rust trait of the same name.
fileprivate protocol FfiConverter {
    associatedtype FfiType
    associatedtype SwiftType

    static func lift(_ value: FfiType) throws -> SwiftType
    static func lower(_ value: SwiftType) -> FfiType
    static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SwiftType
    static func write(_ value: SwiftType, into buf: inout [UInt8])
}

// Types conforming to `Primitive` pass themselves directly over the FFI.
fileprivate protocol FfiConverterPrimitive: FfiConverter where FfiType == SwiftType { }

extension FfiConverterPrimitive {
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func lift(_ value: FfiType) throws -> SwiftType {
        return value
    }

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func lower(_ value: SwiftType) -> FfiType {
        return value
    }
}

// Types conforming to `FfiConverterRustBuffer` lift and lower into a `RustBuffer`.
// Used for complex types where it's hard to write a custom lift/lower.
fileprivate protocol FfiConverterRustBuffer: FfiConverter where FfiType == RustBuffer {}

extension FfiConverterRustBuffer {
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func lift(_ buf: RustBuffer) throws -> SwiftType {
        var reader = createReader(data: Data(rustBuffer: buf))
        let value = try read(from: &reader)
        if hasRemaining(reader) {
            throw UniffiInternalError.incompleteData
        }
        buf.deallocate()
        return value
    }

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func lower(_ value: SwiftType) -> RustBuffer {
          var writer = createWriter()
          write(value, into: &writer)
          return RustBuffer(bytes: writer)
    }
}
// An error type for FFI errors. These errors occur at the UniFFI level, not
// the library level.
fileprivate enum UniffiInternalError: LocalizedError {
    case bufferOverflow
    case incompleteData
    case unexpectedOptionalTag
    case unexpectedEnumCase
    case unexpectedNullPointer
    case unexpectedRustCallStatusCode
    case unexpectedRustCallError
    case unexpectedStaleHandle
    case rustPanic(_ message: String)

    public var errorDescription: String? {
        switch self {
        case .bufferOverflow: return "Reading the requested value would read past the end of the buffer"
        case .incompleteData: return "The buffer still has data after lifting its containing value"
        case .unexpectedOptionalTag: return "Unexpected optional tag; should be 0 or 1"
        case .unexpectedEnumCase: return "Raw enum value doesn't match any cases"
        case .unexpectedNullPointer: return "Raw pointer value was null"
        case .unexpectedRustCallStatusCode: return "Unexpected RustCallStatus code"
        case .unexpectedRustCallError: return "CALL_ERROR but no errorClass specified"
        case .unexpectedStaleHandle: return "The object in the handle map has been dropped already"
        case let .rustPanic(message): return message
        }
    }
}

fileprivate extension NSLock {
    func withLock<T>(f: () throws -> T) rethrows -> T {
        self.lock()
        defer { self.unlock() }
        return try f()
    }
}

fileprivate let CALL_SUCCESS: Int8 = 0
fileprivate let CALL_ERROR: Int8 = 1
fileprivate let CALL_UNEXPECTED_ERROR: Int8 = 2
fileprivate let CALL_CANCELLED: Int8 = 3

fileprivate extension RustCallStatus {
    init() {
        self.init(
            code: CALL_SUCCESS,
            errorBuf: RustBuffer.init(
                capacity: 0,
                len: 0,
                data: nil
            )
        )
    }
}

private func rustCall<T>(_ callback: (UnsafeMutablePointer<RustCallStatus>) -> T) throws -> T {
    let neverThrow: ((RustBuffer) throws -> Never)? = nil
    return try makeRustCall(callback, errorHandler: neverThrow)
}

private func rustCallWithError<T, E: Swift.Error>(
    _ errorHandler: @escaping (RustBuffer) throws -> E,
    _ callback: (UnsafeMutablePointer<RustCallStatus>) -> T) throws -> T {
    try makeRustCall(callback, errorHandler: errorHandler)
}

private func makeRustCall<T, E: Swift.Error>(
    _ callback: (UnsafeMutablePointer<RustCallStatus>) -> T,
    errorHandler: ((RustBuffer) throws -> E)?
) throws -> T {
    uniffiEnsurePrismFfiInitialized()
    var callStatus = RustCallStatus.init()
    let returnedVal = callback(&callStatus)
    try uniffiCheckCallStatus(callStatus: callStatus, errorHandler: errorHandler)
    return returnedVal
}

private func uniffiCheckCallStatus<E: Swift.Error>(
    callStatus: RustCallStatus,
    errorHandler: ((RustBuffer) throws -> E)?
) throws {
    switch callStatus.code {
        case CALL_SUCCESS:
            return

        case CALL_ERROR:
            if let errorHandler = errorHandler {
                throw try errorHandler(callStatus.errorBuf)
            } else {
                callStatus.errorBuf.deallocate()
                throw UniffiInternalError.unexpectedRustCallError
            }

        case CALL_UNEXPECTED_ERROR:
            // When the rust code sees a panic, it tries to construct a RustBuffer
            // with the message.  But if that code panics, then it just sends back
            // an empty buffer.
            if callStatus.errorBuf.len > 0 {
                throw UniffiInternalError.rustPanic(try FfiConverterString.lift(callStatus.errorBuf))
            } else {
                callStatus.errorBuf.deallocate()
                throw UniffiInternalError.rustPanic("Rust panic")
            }

        case CALL_CANCELLED:
            fatalError("Cancellation not supported yet")

        default:
            throw UniffiInternalError.unexpectedRustCallStatusCode
    }
}

private func uniffiTraitInterfaceCall<T>(
    callStatus: UnsafeMutablePointer<RustCallStatus>,
    makeCall: () throws -> T,
    writeReturn: (T) -> ()
) {
    do {
        try writeReturn(makeCall())
    } catch let error {
        callStatus.pointee.code = CALL_UNEXPECTED_ERROR
        callStatus.pointee.errorBuf = FfiConverterString.lower(String(describing: error))
    }
}

private func uniffiTraitInterfaceCallWithError<T, E>(
    callStatus: UnsafeMutablePointer<RustCallStatus>,
    makeCall: () throws -> T,
    writeReturn: (T) -> (),
    lowerError: (E) -> RustBuffer
) {
    do {
        try writeReturn(makeCall())
    } catch let error as E {
        callStatus.pointee.code = CALL_ERROR
        callStatus.pointee.errorBuf = lowerError(error)
    } catch {
        callStatus.pointee.code = CALL_UNEXPECTED_ERROR
        callStatus.pointee.errorBuf = FfiConverterString.lower(String(describing: error))
    }
}
// Initial value and increment amount for handles. 
// These ensure that SWIFT handles always have the lowest bit set
fileprivate let UNIFFI_HANDLEMAP_INITIAL: UInt64 = 1
fileprivate let UNIFFI_HANDLEMAP_DELTA: UInt64 = 2

fileprivate final class UniffiHandleMap<T>: @unchecked Sendable {
    // All mutation happens with this lock held, which is why we implement @unchecked Sendable.
    private let lock = NSLock()
    private var map: [UInt64: T] = [:]
    private var currentHandle: UInt64 = UNIFFI_HANDLEMAP_INITIAL

    func insert(obj: T) -> UInt64 {
        lock.withLock {
            return doInsert(obj)
        }
    }

    // Low-level insert function, this assumes `lock` is held.
    private func doInsert(_ obj: T) -> UInt64 {
        let handle = currentHandle
        currentHandle += UNIFFI_HANDLEMAP_DELTA
        map[handle] = obj
        return handle
    }

     func get(handle: UInt64) throws -> T {
        try lock.withLock {
            guard let obj = map[handle] else {
                throw UniffiInternalError.unexpectedStaleHandle
            }
            return obj
        }
    }

     func clone(handle: UInt64) throws -> UInt64 {
        try lock.withLock {
            guard let obj = map[handle] else {
                throw UniffiInternalError.unexpectedStaleHandle
            }
            return doInsert(obj)
        }
    }

    @discardableResult
    func remove(handle: UInt64) throws -> T {
        try lock.withLock {
            guard let obj = map.removeValue(forKey: handle) else {
                throw UniffiInternalError.unexpectedStaleHandle
            }
            return obj
        }
    }

    var count: Int {
        get {
            map.count
        }
    }
}


// Public interface members begin here.
// Magic number for the Rust proxy to call using the same mechanism as every other method,
// to free the callback once it's dropped by Rust.
private let IDX_CALLBACK_FREE: Int32 = 0
// Callback return codes
private let UNIFFI_CALLBACK_SUCCESS: Int32 = 0
private let UNIFFI_CALLBACK_ERROR: Int32 = 1
private let UNIFFI_CALLBACK_UNEXPECTED_ERROR: Int32 = 2

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterUInt32: FfiConverterPrimitive {
    typealias FfiType = UInt32
    typealias SwiftType = UInt32

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> UInt32 {
        return try lift(readInt(&buf))
    }

    public static func write(_ value: SwiftType, into buf: inout [UInt8]) {
        writeInt(&buf, lower(value))
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterUInt64: FfiConverterPrimitive {
    typealias FfiType = UInt64
    typealias SwiftType = UInt64

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> UInt64 {
        return try lift(readInt(&buf))
    }

    public static func write(_ value: SwiftType, into buf: inout [UInt8]) {
        writeInt(&buf, lower(value))
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterInt64: FfiConverterPrimitive {
    typealias FfiType = Int64
    typealias SwiftType = Int64

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> Int64 {
        return try lift(readInt(&buf))
    }

    public static func write(_ value: Int64, into buf: inout [UInt8]) {
        writeInt(&buf, lower(value))
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterDouble: FfiConverterPrimitive {
    typealias FfiType = Double
    typealias SwiftType = Double

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> Double {
        return try lift(readDouble(&buf))
    }

    public static func write(_ value: Double, into buf: inout [UInt8]) {
        writeDouble(&buf, lower(value))
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterBool : FfiConverter {
    typealias FfiType = Int8
    typealias SwiftType = Bool

    public static func lift(_ value: Int8) throws -> Bool {
        return value != 0
    }

    public static func lower(_ value: Bool) -> Int8 {
        return value ? 1 : 0
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> Bool {
        return try lift(readInt(&buf))
    }

    public static func write(_ value: Bool, into buf: inout [UInt8]) {
        writeInt(&buf, lower(value))
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterString: FfiConverter {
    typealias SwiftType = String
    typealias FfiType = RustBuffer

    public static func lift(_ value: RustBuffer) throws -> String {
        defer {
            value.deallocate()
        }
        if value.data == nil {
            return String()
        }
        let bytes = UnsafeBufferPointer<UInt8>(start: value.data!, count: Int(value.len))
        return String(bytes: bytes, encoding: String.Encoding.utf8)!
    }

    public static func lower(_ value: String) -> RustBuffer {
        return value.utf8CString.withUnsafeBufferPointer { ptr in
            // The swift string gives us int8_t, we want uint8_t.
            ptr.withMemoryRebound(to: UInt8.self) { ptr in
                // The swift string gives us a trailing null byte, we don't want it.
                let buf = UnsafeBufferPointer(rebasing: ptr.prefix(upTo: ptr.count - 1))
                return RustBuffer.from(buf)
            }
        }
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> String {
        let len: Int32 = try readInt(&buf)
        return String(bytes: try readBytes(&buf, count: Int(len)), encoding: String.Encoding.utf8)!
    }

    public static func write(_ value: String, into buf: inout [UInt8]) {
        let len = Int32(value.utf8.count)
        writeInt(&buf, len)
        writeBytes(&buf, value.utf8)
    }
}




/**
 * A cooperative cancel flag. The UI keeps a handle and calls `cancel()`; the core
 * polls it between/within stages and unwinds with [`PrismError::Cancelled`].
 */
public protocol CancelHandleProtocol: AnyObject, Sendable {
    
    func cancel() 
    
    func isCancelled()  -> Bool
    
}
/**
 * A cooperative cancel flag. The UI keeps a handle and calls `cancel()`; the core
 * polls it between/within stages and unwinds with [`PrismError::Cancelled`].
 */
open class CancelHandle: CancelHandleProtocol, @unchecked Sendable {
    fileprivate let handle: UInt64

    /// Used to instantiate a [FFIObject] without an actual handle, for fakes in tests, mostly.
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public struct NoHandle {
        public init() {}
    }

    // TODO: We'd like this to be `private` but for Swifty reasons,
    // we can't implement `FfiConverter` without making this `required` and we can't
    // make it `required` without making it `public`.
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    required public init(unsafeFromHandle handle: UInt64) {
        self.handle = handle
    }

    // This constructor can be used to instantiate a fake object.
    // - Parameter noHandle: Placeholder value so we can have a constructor separate from the default empty one that may be implemented for classes extending [FFIObject].
    //
    // - Warning:
    //     Any object instantiated with this constructor cannot be passed to an actual Rust-backed object. Since there isn't a backing handle the FFI lower functions will crash.
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public init(noHandle: NoHandle) {
        self.handle = 0
    }

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public func uniffiCloneHandle() -> UInt64 {
        return try! rustCall { uniffi_prism_ffi_fn_clone_cancelhandle(self.handle, $0) }
    }
public convenience init() {
    let handle =
        try! rustCall() {
    uniffi_prism_ffi_fn_constructor_cancelhandle_new($0
    )
}
    self.init(unsafeFromHandle: handle)
}

    deinit {
        if handle == 0 {
            // Mock objects have handle=0 don't try to free them
            return
        }

        try! rustCall { uniffi_prism_ffi_fn_free_cancelhandle(handle, $0) }
    }

    

    
open func cancel()  {try! rustCall() {
    uniffi_prism_ffi_fn_method_cancelhandle_cancel(
            self.uniffiCloneHandle(),$0
    )
}
}
    
open func isCancelled() -> Bool  {
    return try!  FfiConverterBool.lift(try! rustCall() {
    uniffi_prism_ffi_fn_method_cancelhandle_is_cancelled(
            self.uniffiCloneHandle(),$0
    )
})
}
    

    
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeCancelHandle: FfiConverter {
    typealias FfiType = UInt64
    typealias SwiftType = CancelHandle

    public static func lift(_ handle: UInt64) throws -> CancelHandle {
        return CancelHandle(unsafeFromHandle: handle)
    }

    public static func lower(_ value: CancelHandle) -> UInt64 {
        return value.uniffiCloneHandle()
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> CancelHandle {
        let handle: UInt64 = try readInt(&buf)
        return try lift(handle)
    }

    public static func write(_ value: CancelHandle, into buf: inout [UInt8]) {
        writeInt(&buf, lower(value))
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeCancelHandle_lift(_ handle: UInt64) throws -> CancelHandle {
    return try FfiConverterTypeCancelHandle.lift(handle)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeCancelHandle_lower(_ value: CancelHandle) -> UInt64 {
    return FfiConverterTypeCancelHandle.lower(value)
}






/**
 * The analysis engine. Construct once; methods are thread-safe.
 */
public protocol EngineProtocol: AnyObject, Sendable {
    
    /**
     * Analyze one image/container/folder. Served from cache when the sha256 is known.
     * Progress flows to `listener`; trip `cancel` to abort.
     */
    func analyze(path: String, listener: ProgressListener, cancel: CancelHandle?) throws  -> AnalysisSummary
    
    /**
     * Export the library as a portable `.zip` bundle (`manifest.json` +
     * `builds.jsonl`) to `out_path` — the format to copy between machines and
     * ingest into the web service. Returns the number of records written.
     */
    func exportBundle(outPath: String) throws  -> UInt64
    
    /**
     * Export the library as JSON Lines to `out_path` (the desktop→web feed). Returns
     * the number of records written.
     */
    func exportJsonl(outPath: String) throws  -> UInt64
    
    /**
     * Number of builds in the local library.
     */
    func librarySize() throws  -> UInt64
    
    /**
     * Distinct systems in the library (for the browser's filter control).
     */
    func librarySystems() throws  -> [String]
    
    /**
     * Recursively list the import units under `root`, sorted: importable files,
     * except that a folder holding one build split across files (a multi-track
     * dump) comes back as a single unit. Used by folder import: the UI walks the
     * list, then calls `analyze` on each and skips non-discs.
     */
    func listFiles(root: String) throws  -> [String]
    
    /**
     * Reload a stored build from cache by sha256 (no adapter run). `None` if absent.
     * Uses the reader, so it works while an import holds the writer.
     */
    func loadBuild(sha256: String) throws  -> AnalysisSummary?
    
    /**
     * Analyze ignoring any cached record: full re-parse and re-hash, replacing
     * the stored record and library row. For builds whose earlier parse is
     * known bad — plain analyze is a cache hit that never re-hashes files.
     */
    func reanalyze(path: String, listener: ProgressListener, cancel: CancelHandle?) throws  -> AnalysisSummary
    
    /**
     * The most recently analyzed builds, newest first.
     */
    func recentBuilds(limit: UInt32) throws  -> [LibraryEntry]
    
    /**
     * Search/browse the library: `search` matches name or system, `system` filters
     * to one, sorted by `sort` (descending when `descending`), paged by limit/offset.
     */
    func searchLibrary(search: String?, system: String?, sort: LibrarySort, descending: Bool, limit: UInt32, offset: UInt32) throws  -> [LibraryEntry]
    
}
/**
 * The analysis engine. Construct once; methods are thread-safe.
 */
open class Engine: EngineProtocol, @unchecked Sendable {
    fileprivate let handle: UInt64

    /// Used to instantiate a [FFIObject] without an actual handle, for fakes in tests, mostly.
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public struct NoHandle {
        public init() {}
    }

    // TODO: We'd like this to be `private` but for Swifty reasons,
    // we can't implement `FfiConverter` without making this `required` and we can't
    // make it `required` without making it `public`.
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    required public init(unsafeFromHandle handle: UInt64) {
        self.handle = handle
    }

    // This constructor can be used to instantiate a fake object.
    // - Parameter noHandle: Placeholder value so we can have a constructor separate from the default empty one that may be implemented for classes extending [FFIObject].
    //
    // - Warning:
    //     Any object instantiated with this constructor cannot be passed to an actual Rust-backed object. Since there isn't a backing handle the FFI lower functions will crash.
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public init(noHandle: NoHandle) {
        self.handle = 0
    }

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public func uniffiCloneHandle() -> UInt64 {
        return try! rustCall { uniffi_prism_ffi_fn_clone_engine(self.handle, $0) }
    }
    /**
     * Build an engine. Supply *either* `adapter_bin` (a bundled launcher; preferred
     * in a shipped app) *or* `adapter_dir` (a uv project, for development). `data_dir`
     * overrides the platform cache/library location.
     */
public convenience init(adapterDir: String?, adapterBin: String?, dataDir: String?)throws  {
    let handle =
        try rustCallWithError(FfiConverterTypePrismError_lift) {
    uniffi_prism_ffi_fn_constructor_engine_new(
        FfiConverterOptionString.lower(adapterDir),
        FfiConverterOptionString.lower(adapterBin),
        FfiConverterOptionString.lower(dataDir),$0
    )
}
    self.init(unsafeFromHandle: handle)
}

    deinit {
        if handle == 0 {
            // Mock objects have handle=0 don't try to free them
            return
        }

        try! rustCall { uniffi_prism_ffi_fn_free_engine(handle, $0) }
    }

    

    
    /**
     * Analyze one image/container/folder. Served from cache when the sha256 is known.
     * Progress flows to `listener`; trip `cancel` to abort.
     */
open func analyze(path: String, listener: ProgressListener, cancel: CancelHandle?)throws  -> AnalysisSummary  {
    return try  FfiConverterTypeAnalysisSummary_lift(try rustCallWithError(FfiConverterTypePrismError_lift) {
    uniffi_prism_ffi_fn_method_engine_analyze(
            self.uniffiCloneHandle(),
        FfiConverterString.lower(path),
        FfiConverterCallbackInterfaceProgressListener_lower(listener),
        FfiConverterOptionTypeCancelHandle.lower(cancel),$0
    )
})
}
    
    /**
     * Export the library as a portable `.zip` bundle (`manifest.json` +
     * `builds.jsonl`) to `out_path` — the format to copy between machines and
     * ingest into the web service. Returns the number of records written.
     */
open func exportBundle(outPath: String)throws  -> UInt64  {
    return try  FfiConverterUInt64.lift(try rustCallWithError(FfiConverterTypePrismError_lift) {
    uniffi_prism_ffi_fn_method_engine_export_bundle(
            self.uniffiCloneHandle(),
        FfiConverterString.lower(outPath),$0
    )
})
}
    
    /**
     * Export the library as JSON Lines to `out_path` (the desktop→web feed). Returns
     * the number of records written.
     */
open func exportJsonl(outPath: String)throws  -> UInt64  {
    return try  FfiConverterUInt64.lift(try rustCallWithError(FfiConverterTypePrismError_lift) {
    uniffi_prism_ffi_fn_method_engine_export_jsonl(
            self.uniffiCloneHandle(),
        FfiConverterString.lower(outPath),$0
    )
})
}
    
    /**
     * Number of builds in the local library.
     */
open func librarySize()throws  -> UInt64  {
    return try  FfiConverterUInt64.lift(try rustCallWithError(FfiConverterTypePrismError_lift) {
    uniffi_prism_ffi_fn_method_engine_library_size(
            self.uniffiCloneHandle(),$0
    )
})
}
    
    /**
     * Distinct systems in the library (for the browser's filter control).
     */
open func librarySystems()throws  -> [String]  {
    return try  FfiConverterSequenceString.lift(try rustCallWithError(FfiConverterTypePrismError_lift) {
    uniffi_prism_ffi_fn_method_engine_library_systems(
            self.uniffiCloneHandle(),$0
    )
})
}
    
    /**
     * Recursively list the import units under `root`, sorted: importable files,
     * except that a folder holding one build split across files (a multi-track
     * dump) comes back as a single unit. Used by folder import: the UI walks the
     * list, then calls `analyze` on each and skips non-discs.
     */
open func listFiles(root: String)throws  -> [String]  {
    return try  FfiConverterSequenceString.lift(try rustCallWithError(FfiConverterTypePrismError_lift) {
    uniffi_prism_ffi_fn_method_engine_list_files(
            self.uniffiCloneHandle(),
        FfiConverterString.lower(root),$0
    )
})
}
    
    /**
     * Reload a stored build from cache by sha256 (no adapter run). `None` if absent.
     * Uses the reader, so it works while an import holds the writer.
     */
open func loadBuild(sha256: String)throws  -> AnalysisSummary?  {
    return try  FfiConverterOptionTypeAnalysisSummary.lift(try rustCallWithError(FfiConverterTypePrismError_lift) {
    uniffi_prism_ffi_fn_method_engine_load_build(
            self.uniffiCloneHandle(),
        FfiConverterString.lower(sha256),$0
    )
})
}
    
    /**
     * Analyze ignoring any cached record: full re-parse and re-hash, replacing
     * the stored record and library row. For builds whose earlier parse is
     * known bad — plain analyze is a cache hit that never re-hashes files.
     */
open func reanalyze(path: String, listener: ProgressListener, cancel: CancelHandle?)throws  -> AnalysisSummary  {
    return try  FfiConverterTypeAnalysisSummary_lift(try rustCallWithError(FfiConverterTypePrismError_lift) {
    uniffi_prism_ffi_fn_method_engine_reanalyze(
            self.uniffiCloneHandle(),
        FfiConverterString.lower(path),
        FfiConverterCallbackInterfaceProgressListener_lower(listener),
        FfiConverterOptionTypeCancelHandle.lower(cancel),$0
    )
})
}
    
    /**
     * The most recently analyzed builds, newest first.
     */
open func recentBuilds(limit: UInt32)throws  -> [LibraryEntry]  {
    return try  FfiConverterSequenceTypeLibraryEntry.lift(try rustCallWithError(FfiConverterTypePrismError_lift) {
    uniffi_prism_ffi_fn_method_engine_recent_builds(
            self.uniffiCloneHandle(),
        FfiConverterUInt32.lower(limit),$0
    )
})
}
    
    /**
     * Search/browse the library: `search` matches name or system, `system` filters
     * to one, sorted by `sort` (descending when `descending`), paged by limit/offset.
     */
open func searchLibrary(search: String?, system: String?, sort: LibrarySort, descending: Bool, limit: UInt32, offset: UInt32)throws  -> [LibraryEntry]  {
    return try  FfiConverterSequenceTypeLibraryEntry.lift(try rustCallWithError(FfiConverterTypePrismError_lift) {
    uniffi_prism_ffi_fn_method_engine_search_library(
            self.uniffiCloneHandle(),
        FfiConverterOptionString.lower(search),
        FfiConverterOptionString.lower(system),
        FfiConverterTypeLibrarySort_lower(sort),
        FfiConverterBool.lower(descending),
        FfiConverterUInt32.lower(limit),
        FfiConverterUInt32.lower(offset),$0
    )
})
}
    

    
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeEngine: FfiConverter {
    typealias FfiType = UInt64
    typealias SwiftType = Engine

    public static func lift(_ handle: UInt64) throws -> Engine {
        return Engine(unsafeFromHandle: handle)
    }

    public static func lower(_ value: Engine) -> UInt64 {
        return value.uniffiCloneHandle()
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> Engine {
        let handle: UInt64 = try readInt(&buf)
        return try lift(handle)
    }

    public static func write(_ value: Engine, into buf: inout [UInt8]) {
        writeInt(&buf, lower(value))
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeEngine_lift(_ handle: UInt64) throws -> Engine {
    return try FfiConverterTypeEngine.lift(handle)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeEngine_lower(_ value: Engine) -> UInt64 {
    return FfiConverterTypeEngine.lower(value)
}




/**
 * Everything the GUI needs to render one analyzed image.
 */
public struct AnalysisSummary: Equatable, Hashable {
    public var sha256: String
    public var name: String
    public var system: String
    public var title: String?
    public var fromCache: Bool
    public var fileCount: UInt64
    public var totalSize: UInt64
    public var jsonPath: String
    public var tree: [FileNode]
    /**
     * Pretty-printed canonical XML DAT.
     */
    public var xml: String
    /**
     * Pretty-printed canonical JSON record.
     */
    public var json: String
    /**
     * Viewable assets. `None` = extraction never ran on this record.
     */
    public var assets: [AssetInfo]?

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(sha256: String, name: String, system: String, title: String?, fromCache: Bool, fileCount: UInt64, totalSize: UInt64, jsonPath: String, tree: [FileNode], 
        /**
         * Pretty-printed canonical XML DAT.
         */xml: String, 
        /**
         * Pretty-printed canonical JSON record.
         */json: String, 
        /**
         * Viewable assets. `None` = extraction never ran on this record.
         */assets: [AssetInfo]?) {
        self.sha256 = sha256
        self.name = name
        self.system = system
        self.title = title
        self.fromCache = fromCache
        self.fileCount = fileCount
        self.totalSize = totalSize
        self.jsonPath = jsonPath
        self.tree = tree
        self.xml = xml
        self.json = json
        self.assets = assets
    }

    

    
}

#if compiler(>=6)
extension AnalysisSummary: Sendable {}
#endif

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeAnalysisSummary: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> AnalysisSummary {
        return
            try AnalysisSummary(
                sha256: FfiConverterString.read(from: &buf), 
                name: FfiConverterString.read(from: &buf), 
                system: FfiConverterString.read(from: &buf), 
                title: FfiConverterOptionString.read(from: &buf), 
                fromCache: FfiConverterBool.read(from: &buf), 
                fileCount: FfiConverterUInt64.read(from: &buf), 
                totalSize: FfiConverterUInt64.read(from: &buf), 
                jsonPath: FfiConverterString.read(from: &buf), 
                tree: FfiConverterSequenceTypeFileNode.read(from: &buf), 
                xml: FfiConverterString.read(from: &buf), 
                json: FfiConverterString.read(from: &buf), 
                assets: FfiConverterOptionSequenceTypeAssetInfo.read(from: &buf)
        )
    }

    public static func write(_ value: AnalysisSummary, into buf: inout [UInt8]) {
        FfiConverterString.write(value.sha256, into: &buf)
        FfiConverterString.write(value.name, into: &buf)
        FfiConverterString.write(value.system, into: &buf)
        FfiConverterOptionString.write(value.title, into: &buf)
        FfiConverterBool.write(value.fromCache, into: &buf)
        FfiConverterUInt64.write(value.fileCount, into: &buf)
        FfiConverterUInt64.write(value.totalSize, into: &buf)
        FfiConverterString.write(value.jsonPath, into: &buf)
        FfiConverterSequenceTypeFileNode.write(value.tree, into: &buf)
        FfiConverterString.write(value.xml, into: &buf)
        FfiConverterString.write(value.json, into: &buf)
        FfiConverterOptionSequenceTypeAssetInfo.write(value.assets, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeAnalysisSummary_lift(_ buf: RustBuffer) throws -> AnalysisSummary {
    return try FfiConverterTypeAnalysisSummary.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeAnalysisSummary_lower(_ value: AnalysisSummary) -> RustBuffer {
    return FfiConverterTypeAnalysisSummary.lower(value)
}


/**
 * One browser-viewable asset extracted from the build (image/audio/video/text).
 */
public struct AssetInfo: Equatable, Hashable {
    /**
     * Full path from the volume root — matches the contents tree.
     */
    public var path: String
    public var sha256: String
    public var size: UInt64
    public var mime: String
    public var kind: String
    /**
     * Absolute path of the blob in the local store, when present.
     */
    public var blobPath: String?

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(
        /**
         * Full path from the volume root — matches the contents tree.
         */path: String, sha256: String, size: UInt64, mime: String, kind: String, 
        /**
         * Absolute path of the blob in the local store, when present.
         */blobPath: String?) {
        self.path = path
        self.sha256 = sha256
        self.size = size
        self.mime = mime
        self.kind = kind
        self.blobPath = blobPath
    }

    

    
}

#if compiler(>=6)
extension AssetInfo: Sendable {}
#endif

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeAssetInfo: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> AssetInfo {
        return
            try AssetInfo(
                path: FfiConverterString.read(from: &buf), 
                sha256: FfiConverterString.read(from: &buf), 
                size: FfiConverterUInt64.read(from: &buf), 
                mime: FfiConverterString.read(from: &buf), 
                kind: FfiConverterString.read(from: &buf), 
                blobPath: FfiConverterOptionString.read(from: &buf)
        )
    }

    public static func write(_ value: AssetInfo, into buf: inout [UInt8]) {
        FfiConverterString.write(value.path, into: &buf)
        FfiConverterString.write(value.sha256, into: &buf)
        FfiConverterUInt64.write(value.size, into: &buf)
        FfiConverterString.write(value.mime, into: &buf)
        FfiConverterString.write(value.kind, into: &buf)
        FfiConverterOptionString.write(value.blobPath, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeAssetInfo_lift(_ buf: RustBuffer) throws -> AssetInfo {
    return try FfiConverterTypeAssetInfo.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeAssetInfo_lower(_ value: AssetInfo) -> RustBuffer {
    return FfiConverterTypeAssetInfo.lower(value)
}


/**
 * One node of the on-disc filesystem tree (recursive via `children`).
 */
public struct FileNode: Equatable, Hashable {
    public var name: String
    public var isDir: Bool
    public var size: UInt64?
    public var date: String?
    public var md5: String?
    public var sha1: String?
    public var sha256: String?
    public var unreadable: Bool
    public var children: [FileNode]

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(name: String, isDir: Bool, size: UInt64?, date: String?, md5: String?, sha1: String?, sha256: String?, unreadable: Bool, children: [FileNode]) {
        self.name = name
        self.isDir = isDir
        self.size = size
        self.date = date
        self.md5 = md5
        self.sha1 = sha1
        self.sha256 = sha256
        self.unreadable = unreadable
        self.children = children
    }

    

    
}

#if compiler(>=6)
extension FileNode: Sendable {}
#endif

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeFileNode: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> FileNode {
        return
            try FileNode(
                name: FfiConverterString.read(from: &buf), 
                isDir: FfiConverterBool.read(from: &buf), 
                size: FfiConverterOptionUInt64.read(from: &buf), 
                date: FfiConverterOptionString.read(from: &buf), 
                md5: FfiConverterOptionString.read(from: &buf), 
                sha1: FfiConverterOptionString.read(from: &buf), 
                sha256: FfiConverterOptionString.read(from: &buf), 
                unreadable: FfiConverterBool.read(from: &buf), 
                children: FfiConverterSequenceTypeFileNode.read(from: &buf)
        )
    }

    public static func write(_ value: FileNode, into buf: inout [UInt8]) {
        FfiConverterString.write(value.name, into: &buf)
        FfiConverterBool.write(value.isDir, into: &buf)
        FfiConverterOptionUInt64.write(value.size, into: &buf)
        FfiConverterOptionString.write(value.date, into: &buf)
        FfiConverterOptionString.write(value.md5, into: &buf)
        FfiConverterOptionString.write(value.sha1, into: &buf)
        FfiConverterOptionString.write(value.sha256, into: &buf)
        FfiConverterBool.write(value.unreadable, into: &buf)
        FfiConverterSequenceTypeFileNode.write(value.children, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeFileNode_lift(_ buf: RustBuffer) throws -> FileNode {
    return try FfiConverterTypeFileNode.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeFileNode_lower(_ value: FileNode) -> RustBuffer {
    return FfiConverterTypeFileNode.lower(value)
}


/**
 * A library entry for the recent-builds list and the library browser.
 */
public struct LibraryEntry: Equatable, Hashable {
    public var sha256: String
    public var name: String
    public var system: String
    public var fileCount: UInt64
    public var totalSize: UInt64
    /**
     * Unix seconds of last analysis.
     */
    public var analyzedAt: Int64

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(sha256: String, name: String, system: String, fileCount: UInt64, totalSize: UInt64, 
        /**
         * Unix seconds of last analysis.
         */analyzedAt: Int64) {
        self.sha256 = sha256
        self.name = name
        self.system = system
        self.fileCount = fileCount
        self.totalSize = totalSize
        self.analyzedAt = analyzedAt
    }

    

    
}

#if compiler(>=6)
extension LibraryEntry: Sendable {}
#endif

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeLibraryEntry: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> LibraryEntry {
        return
            try LibraryEntry(
                sha256: FfiConverterString.read(from: &buf), 
                name: FfiConverterString.read(from: &buf), 
                system: FfiConverterString.read(from: &buf), 
                fileCount: FfiConverterUInt64.read(from: &buf), 
                totalSize: FfiConverterUInt64.read(from: &buf), 
                analyzedAt: FfiConverterInt64.read(from: &buf)
        )
    }

    public static func write(_ value: LibraryEntry, into buf: inout [UInt8]) {
        FfiConverterString.write(value.sha256, into: &buf)
        FfiConverterString.write(value.name, into: &buf)
        FfiConverterString.write(value.system, into: &buf)
        FfiConverterUInt64.write(value.fileCount, into: &buf)
        FfiConverterUInt64.write(value.totalSize, into: &buf)
        FfiConverterInt64.write(value.analyzedAt, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeLibraryEntry_lift(_ buf: RustBuffer) throws -> LibraryEntry {
    return try FfiConverterTypeLibraryEntry.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeLibraryEntry_lower(_ value: LibraryEntry) -> RustBuffer {
    return FfiConverterTypeLibraryEntry.lower(value)
}


public enum PrismError: Swift.Error, Equatable, Hashable, Foundation.LocalizedError {

    
    
    case Cancelled
    case Failed(message: String
    )

    

    

    
    public var errorDescription: String? {
        String(reflecting: self)
    }
    
}

#if compiler(>=6)
extension PrismError: Sendable {}
#endif

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypePrismError: FfiConverterRustBuffer {
    typealias SwiftType = PrismError

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> PrismError {
        let variant: Int32 = try readInt(&buf)
        switch variant {

        

        
        case 1: return .Cancelled
        case 2: return .Failed(
            message: try FfiConverterString.read(from: &buf)
            )

         default: throw UniffiInternalError.unexpectedEnumCase
        }
    }

    public static func write(_ value: PrismError, into buf: inout [UInt8]) {
        switch value {

        

        
        
        case .Cancelled:
            writeInt(&buf, Int32(1))
        
        
        case let .Failed(message):
            writeInt(&buf, Int32(2))
            FfiConverterString.write(message, into: &buf)
            
        }
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypePrismError_lift(_ buf: RustBuffer) throws -> PrismError {
    return try FfiConverterTypePrismError.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypePrismError_lower(_ value: PrismError) -> RustBuffer {
    return FfiConverterTypePrismError.lower(value)
}

// Note that we don't yet support `indirect` for enums.
// See https://github.com/mozilla/uniffi-rs/issues/396 for further discussion.
/**
 * Column the library browser sorts on.
 */

public enum LibrarySort: Equatable, Hashable {
    
    case name
    case system
    case files
    case size
    case date





}

#if compiler(>=6)
extension LibrarySort: Sendable {}
#endif

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeLibrarySort: FfiConverterRustBuffer {
    typealias SwiftType = LibrarySort

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> LibrarySort {
        let variant: Int32 = try readInt(&buf)
        switch variant {
        
        case 1: return .name
        
        case 2: return .system
        
        case 3: return .files
        
        case 4: return .size
        
        case 5: return .date
        
        default: throw UniffiInternalError.unexpectedEnumCase
        }
    }

    public static func write(_ value: LibrarySort, into buf: inout [UInt8]) {
        switch value {
        
        
        case .name:
            writeInt(&buf, Int32(1))
        
        
        case .system:
            writeInt(&buf, Int32(2))
        
        
        case .files:
            writeInt(&buf, Int32(3))
        
        
        case .size:
            writeInt(&buf, Int32(4))
        
        
        case .date:
            writeInt(&buf, Int32(5))
        
        }
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeLibrarySort_lift(_ buf: RustBuffer) throws -> LibrarySort {
    return try FfiConverterTypeLibrarySort.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeLibrarySort_lower(_ value: LibrarySort) -> RustBuffer {
    return FfiConverterTypeLibrarySort.lower(value)
}





/**
 * Implemented on the Swift side; receives progress on a background thread.
 */
public protocol ProgressListener: AnyObject, Sendable {
    
    /**
     * Batch-level: starting item `index` of `total`.
     */
    func onBatch(index: UInt64, total: UInt64, name: String) 
    
    /**
     * A counter opened. `total == None` ⇒ indeterminate.
     */
    func onCounterOpen(id: UInt64, label: String, unit: String, total: Double?) 
    
    /**
     * Counter advanced to `count`.
     */
    func onProgress(id: UInt64, count: Double) 
    
    /**
     * Counter closed.
     */
    func onCounterClose(id: UInt64) 
    
    /**
     * Free-text status line.
     */
    func onMessage(text: String) 
    
}


// Put the implementation in a struct so we don't pollute the top-level namespace
fileprivate struct UniffiCallbackInterfaceProgressListener {

    // Create the VTable using a series of closures.
    // Swift automatically converts these into C callback functions.
    //
    // Store the vtable directly.
    static let vtable: UniffiVTableCallbackInterfaceProgressListener = UniffiVTableCallbackInterfaceProgressListener(
        uniffiFree: { (uniffiHandle: UInt64) -> () in
            do {
                try FfiConverterCallbackInterfaceProgressListener.handleMap.remove(handle: uniffiHandle)
            } catch {
                print("Uniffi callback interface ProgressListener: handle missing in uniffiFree")
            }
        },
        uniffiClone: { (uniffiHandle: UInt64) -> UInt64 in
            do {
                return try FfiConverterCallbackInterfaceProgressListener.handleMap.clone(handle: uniffiHandle)
            } catch {
                fatalError("Uniffi callback interface ProgressListener: handle missing in uniffiClone")
            }
        },
        onBatch: { (
            uniffiHandle: UInt64,
            index: UInt64,
            total: UInt64,
            name: RustBuffer,
            uniffiOutReturn: UnsafeMutableRawPointer,
            uniffiCallStatus: UnsafeMutablePointer<RustCallStatus>
        ) in
            let makeCall = {
                () throws -> () in
                guard let uniffiObj = try? FfiConverterCallbackInterfaceProgressListener.handleMap.get(handle: uniffiHandle) else {
                    throw UniffiInternalError.unexpectedStaleHandle
                }
                return uniffiObj.onBatch(
                     index: try FfiConverterUInt64.lift(index),
                     total: try FfiConverterUInt64.lift(total),
                     name: try FfiConverterString.lift(name)
                )
            }

            
            let writeReturn = { () }
            uniffiTraitInterfaceCall(
                callStatus: uniffiCallStatus,
                makeCall: makeCall,
                writeReturn: writeReturn
            )
        },
        onCounterOpen: { (
            uniffiHandle: UInt64,
            id: UInt64,
            label: RustBuffer,
            unit: RustBuffer,
            total: RustBuffer,
            uniffiOutReturn: UnsafeMutableRawPointer,
            uniffiCallStatus: UnsafeMutablePointer<RustCallStatus>
        ) in
            let makeCall = {
                () throws -> () in
                guard let uniffiObj = try? FfiConverterCallbackInterfaceProgressListener.handleMap.get(handle: uniffiHandle) else {
                    throw UniffiInternalError.unexpectedStaleHandle
                }
                return uniffiObj.onCounterOpen(
                     id: try FfiConverterUInt64.lift(id),
                     label: try FfiConverterString.lift(label),
                     unit: try FfiConverterString.lift(unit),
                     total: try FfiConverterOptionDouble.lift(total)
                )
            }

            
            let writeReturn = { () }
            uniffiTraitInterfaceCall(
                callStatus: uniffiCallStatus,
                makeCall: makeCall,
                writeReturn: writeReturn
            )
        },
        onProgress: { (
            uniffiHandle: UInt64,
            id: UInt64,
            count: Double,
            uniffiOutReturn: UnsafeMutableRawPointer,
            uniffiCallStatus: UnsafeMutablePointer<RustCallStatus>
        ) in
            let makeCall = {
                () throws -> () in
                guard let uniffiObj = try? FfiConverterCallbackInterfaceProgressListener.handleMap.get(handle: uniffiHandle) else {
                    throw UniffiInternalError.unexpectedStaleHandle
                }
                return uniffiObj.onProgress(
                     id: try FfiConverterUInt64.lift(id),
                     count: try FfiConverterDouble.lift(count)
                )
            }

            
            let writeReturn = { () }
            uniffiTraitInterfaceCall(
                callStatus: uniffiCallStatus,
                makeCall: makeCall,
                writeReturn: writeReturn
            )
        },
        onCounterClose: { (
            uniffiHandle: UInt64,
            id: UInt64,
            uniffiOutReturn: UnsafeMutableRawPointer,
            uniffiCallStatus: UnsafeMutablePointer<RustCallStatus>
        ) in
            let makeCall = {
                () throws -> () in
                guard let uniffiObj = try? FfiConverterCallbackInterfaceProgressListener.handleMap.get(handle: uniffiHandle) else {
                    throw UniffiInternalError.unexpectedStaleHandle
                }
                return uniffiObj.onCounterClose(
                     id: try FfiConverterUInt64.lift(id)
                )
            }

            
            let writeReturn = { () }
            uniffiTraitInterfaceCall(
                callStatus: uniffiCallStatus,
                makeCall: makeCall,
                writeReturn: writeReturn
            )
        },
        onMessage: { (
            uniffiHandle: UInt64,
            text: RustBuffer,
            uniffiOutReturn: UnsafeMutableRawPointer,
            uniffiCallStatus: UnsafeMutablePointer<RustCallStatus>
        ) in
            let makeCall = {
                () throws -> () in
                guard let uniffiObj = try? FfiConverterCallbackInterfaceProgressListener.handleMap.get(handle: uniffiHandle) else {
                    throw UniffiInternalError.unexpectedStaleHandle
                }
                return uniffiObj.onMessage(
                     text: try FfiConverterString.lift(text)
                )
            }

            
            let writeReturn = { () }
            uniffiTraitInterfaceCall(
                callStatus: uniffiCallStatus,
                makeCall: makeCall,
                writeReturn: writeReturn
            )
        }
    )

    // Rust stores this pointer for future callback invocations, so it must live
    // for the process lifetime (not just for the init function call).
    static let vtablePtr: UnsafePointer<UniffiVTableCallbackInterfaceProgressListener> = {
        let ptr = UnsafeMutablePointer<UniffiVTableCallbackInterfaceProgressListener>.allocate(capacity: 1)
        ptr.initialize(to: vtable)
        return UnsafePointer(ptr)
    }()
}

private func uniffiCallbackInitProgressListener() {
    uniffi_prism_ffi_fn_init_callback_vtable_progresslistener(UniffiCallbackInterfaceProgressListener.vtablePtr)
}

// FfiConverter protocol for callback interfaces
#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterCallbackInterfaceProgressListener {
    fileprivate static let handleMap = UniffiHandleMap<ProgressListener>()
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
extension FfiConverterCallbackInterfaceProgressListener : FfiConverter {
    typealias SwiftType = ProgressListener
    typealias FfiType = UInt64

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func lift(_ handle: UInt64) throws -> SwiftType {
        try handleMap.get(handle: handle)
    }

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SwiftType {
        let handle: UInt64 = try readInt(&buf)
        return try lift(handle)
    }

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func lower(_ v: SwiftType) -> UInt64 {
        return handleMap.insert(obj: v)
    }

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func write(_ v: SwiftType, into buf: inout [UInt8]) {
        writeInt(&buf, lower(v))
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterCallbackInterfaceProgressListener_lift(_ handle: UInt64) throws -> ProgressListener {
    return try FfiConverterCallbackInterfaceProgressListener.lift(handle)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterCallbackInterfaceProgressListener_lower(_ v: ProgressListener) -> UInt64 {
    return FfiConverterCallbackInterfaceProgressListener.lower(v)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterOptionUInt64: FfiConverterRustBuffer {
    typealias SwiftType = UInt64?

    public static func write(_ value: SwiftType, into buf: inout [UInt8]) {
        guard let value = value else {
            writeInt(&buf, Int8(0))
            return
        }
        writeInt(&buf, Int8(1))
        FfiConverterUInt64.write(value, into: &buf)
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SwiftType {
        switch try readInt(&buf) as Int8 {
        case 0: return nil
        case 1: return try FfiConverterUInt64.read(from: &buf)
        default: throw UniffiInternalError.unexpectedOptionalTag
        }
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterOptionDouble: FfiConverterRustBuffer {
    typealias SwiftType = Double?

    public static func write(_ value: SwiftType, into buf: inout [UInt8]) {
        guard let value = value else {
            writeInt(&buf, Int8(0))
            return
        }
        writeInt(&buf, Int8(1))
        FfiConverterDouble.write(value, into: &buf)
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SwiftType {
        switch try readInt(&buf) as Int8 {
        case 0: return nil
        case 1: return try FfiConverterDouble.read(from: &buf)
        default: throw UniffiInternalError.unexpectedOptionalTag
        }
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterOptionString: FfiConverterRustBuffer {
    typealias SwiftType = String?

    public static func write(_ value: SwiftType, into buf: inout [UInt8]) {
        guard let value = value else {
            writeInt(&buf, Int8(0))
            return
        }
        writeInt(&buf, Int8(1))
        FfiConverterString.write(value, into: &buf)
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SwiftType {
        switch try readInt(&buf) as Int8 {
        case 0: return nil
        case 1: return try FfiConverterString.read(from: &buf)
        default: throw UniffiInternalError.unexpectedOptionalTag
        }
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterOptionTypeCancelHandle: FfiConverterRustBuffer {
    typealias SwiftType = CancelHandle?

    public static func write(_ value: SwiftType, into buf: inout [UInt8]) {
        guard let value = value else {
            writeInt(&buf, Int8(0))
            return
        }
        writeInt(&buf, Int8(1))
        FfiConverterTypeCancelHandle.write(value, into: &buf)
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SwiftType {
        switch try readInt(&buf) as Int8 {
        case 0: return nil
        case 1: return try FfiConverterTypeCancelHandle.read(from: &buf)
        default: throw UniffiInternalError.unexpectedOptionalTag
        }
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterOptionTypeAnalysisSummary: FfiConverterRustBuffer {
    typealias SwiftType = AnalysisSummary?

    public static func write(_ value: SwiftType, into buf: inout [UInt8]) {
        guard let value = value else {
            writeInt(&buf, Int8(0))
            return
        }
        writeInt(&buf, Int8(1))
        FfiConverterTypeAnalysisSummary.write(value, into: &buf)
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SwiftType {
        switch try readInt(&buf) as Int8 {
        case 0: return nil
        case 1: return try FfiConverterTypeAnalysisSummary.read(from: &buf)
        default: throw UniffiInternalError.unexpectedOptionalTag
        }
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterOptionSequenceTypeAssetInfo: FfiConverterRustBuffer {
    typealias SwiftType = [AssetInfo]?

    public static func write(_ value: SwiftType, into buf: inout [UInt8]) {
        guard let value = value else {
            writeInt(&buf, Int8(0))
            return
        }
        writeInt(&buf, Int8(1))
        FfiConverterSequenceTypeAssetInfo.write(value, into: &buf)
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SwiftType {
        switch try readInt(&buf) as Int8 {
        case 0: return nil
        case 1: return try FfiConverterSequenceTypeAssetInfo.read(from: &buf)
        default: throw UniffiInternalError.unexpectedOptionalTag
        }
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterSequenceString: FfiConverterRustBuffer {
    typealias SwiftType = [String]

    public static func write(_ value: [String], into buf: inout [UInt8]) {
        let len = Int32(value.count)
        writeInt(&buf, len)
        for item in value {
            FfiConverterString.write(item, into: &buf)
        }
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> [String] {
        let len: Int32 = try readInt(&buf)
        var seq = [String]()
        seq.reserveCapacity(Int(len))
        for _ in 0 ..< len {
            seq.append(try FfiConverterString.read(from: &buf))
        }
        return seq
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterSequenceTypeAssetInfo: FfiConverterRustBuffer {
    typealias SwiftType = [AssetInfo]

    public static func write(_ value: [AssetInfo], into buf: inout [UInt8]) {
        let len = Int32(value.count)
        writeInt(&buf, len)
        for item in value {
            FfiConverterTypeAssetInfo.write(item, into: &buf)
        }
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> [AssetInfo] {
        let len: Int32 = try readInt(&buf)
        var seq = [AssetInfo]()
        seq.reserveCapacity(Int(len))
        for _ in 0 ..< len {
            seq.append(try FfiConverterTypeAssetInfo.read(from: &buf))
        }
        return seq
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterSequenceTypeFileNode: FfiConverterRustBuffer {
    typealias SwiftType = [FileNode]

    public static func write(_ value: [FileNode], into buf: inout [UInt8]) {
        let len = Int32(value.count)
        writeInt(&buf, len)
        for item in value {
            FfiConverterTypeFileNode.write(item, into: &buf)
        }
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> [FileNode] {
        let len: Int32 = try readInt(&buf)
        var seq = [FileNode]()
        seq.reserveCapacity(Int(len))
        for _ in 0 ..< len {
            seq.append(try FfiConverterTypeFileNode.read(from: &buf))
        }
        return seq
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterSequenceTypeLibraryEntry: FfiConverterRustBuffer {
    typealias SwiftType = [LibraryEntry]

    public static func write(_ value: [LibraryEntry], into buf: inout [UInt8]) {
        let len = Int32(value.count)
        writeInt(&buf, len)
        for item in value {
            FfiConverterTypeLibraryEntry.write(item, into: &buf)
        }
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> [LibraryEntry] {
        let len: Int32 = try readInt(&buf)
        var seq = [LibraryEntry]()
        seq.reserveCapacity(Int(len))
        for _ in 0 ..< len {
            seq.append(try FfiConverterTypeLibraryEntry.read(from: &buf))
        }
        return seq
    }
}
/**
 * Whether `root` is a folder holding ONE build split across files (a multi-track
 * dump) rather than a collection of separate images — the UI routes such folders
 * to `analyze` instead of batch import. See `prism_core::folder_is_single_build`.
 */
public func folderIsSingleBuild(root: String) -> Bool  {
    return try!  FfiConverterBool.lift(try! rustCall() {
    uniffi_prism_ffi_fn_func_folder_is_single_build(
        FfiConverterString.lower(root),$0
    )
})
}

private enum InitializationResult {
    case ok
    case contractVersionMismatch
    case apiChecksumMismatch
}
// Use a global variable to perform the versioning checks. Swift ensures that
// the code inside is only computed once.
private let initializationResult: InitializationResult = {
    // Get the bindings contract version from our ComponentInterface
    let bindings_contract_version = 30
    // Get the scaffolding contract version by calling the into the dylib
    let scaffolding_contract_version = ffi_prism_ffi_uniffi_contract_version()
    if bindings_contract_version != scaffolding_contract_version {
        return InitializationResult.contractVersionMismatch
    }
    if (uniffi_prism_ffi_checksum_func_folder_is_single_build() != 6360) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_prism_ffi_checksum_method_cancelhandle_cancel() != 40201) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_prism_ffi_checksum_method_cancelhandle_is_cancelled() != 17041) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_prism_ffi_checksum_method_engine_analyze() != 11313) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_prism_ffi_checksum_method_engine_export_bundle() != 38085) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_prism_ffi_checksum_method_engine_export_jsonl() != 34610) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_prism_ffi_checksum_method_engine_library_size() != 11031) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_prism_ffi_checksum_method_engine_library_systems() != 32687) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_prism_ffi_checksum_method_engine_list_files() != 51427) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_prism_ffi_checksum_method_engine_load_build() != 49667) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_prism_ffi_checksum_method_engine_reanalyze() != 14905) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_prism_ffi_checksum_method_engine_recent_builds() != 34130) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_prism_ffi_checksum_method_engine_search_library() != 55098) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_prism_ffi_checksum_constructor_cancelhandle_new() != 13737) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_prism_ffi_checksum_constructor_engine_new() != 35085) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_prism_ffi_checksum_method_progresslistener_on_batch() != 4925) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_prism_ffi_checksum_method_progresslistener_on_counter_open() != 34203) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_prism_ffi_checksum_method_progresslistener_on_progress() != 38671) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_prism_ffi_checksum_method_progresslistener_on_counter_close() != 52862) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_prism_ffi_checksum_method_progresslistener_on_message() != 40319) {
        return InitializationResult.apiChecksumMismatch
    }

    uniffiCallbackInitProgressListener()
    return InitializationResult.ok
}()

// Make the ensure init function public so that other modules which have external type references to
// our types can call it.
public func uniffiEnsurePrismFfiInitialized() {
    switch initializationResult {
    case .ok:
        break
    case .contractVersionMismatch:
        fatalError("UniFFI contract version mismatch: try cleaning and rebuilding your project")
    case .apiChecksumMismatch:
        fatalError("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
}

// swiftlint:enable all